# Generated by Django 4.0.5 on 2022-06-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torran_api', '0002_alter_files_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='category',
            field=models.CharField(choices=[('AM', 'Adult Movie'), ('MO', 'Movie and series'), ('MS', 'Music'), ('SO', 'Software and app'), ('GM', 'Game')], max_length=20),
        ),
    ]
