# Generated by Django 4.0.5 on 2022-06-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torran_api', '0003_alter_files_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='Downloads',
            field=models.IntegerField(default=0),
        ),
    ]
