# Generated by Django 4.0.5 on 2022-06-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torran_api', '0004_alter_files_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='magnet_url',
            field=models.TextField(),
        ),
    ]
