# Generated by Django 4.0.5 on 2022-06-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torran_api', '0005_alter_files_info_alter_files_magnet_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='torrent_file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
