# Generated by Django 4.0.5 on 2022-06-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torran_api', '0006_files_torrent_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='torrent_file',
        ),
    ]
