# Generated by Django 4.0.6 on 2022-08-02 19:33

from django.db import migrations, models
import torran_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('torran_api', '0008_alter_files_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=torran_api.models.upload_to),
        ),
        migrations.AlterField(
            model_name='files',
            name='category',
            field=models.CharField(choices=[('MO', 'Movie'), ('SE', 'series'), ('MS', 'Music'), ('SO', 'Software and app'), ('GM', 'Game')], max_length=20),
        ),
    ]
